# .github/workflows/test_vacuum.yaml
name: "Lint OpenAPI Spec and Comment on PR"

on:
  push:
    branches:
      - feature/docker-lint
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: write

jobs:
  vacuum-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run vacuum-lint composite action
        uses: ./
        with:
          openapi_path: "sample-specs/burgershop.yaml"
