name: "Lint OpenAPI specification using vacuum"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  vacuum-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run OpenAPI lint with vacuum
        uses: ./
        with:
          show_rules: true
          fail_on_error: true
          minimum_score: 80
          print_logs: false
          openapi_path: "sample-specs/burgershop.yaml"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run OpenAPI lint with vacuum and custom ruleset
        uses: ./
        with:
          show_rules: true
          fail_on_error: true
          minimum_score: 80
          print_logs: true
          ruleset: "sample-specs/ruleset.yaml"
          openapi_path: "sample-specs/burgershop.yaml"
          github_token: ${{ secrets.GITHUB_TOKEN }}
