name: "Lint OpenAPI Spec and Comment on PR"

on:
  push:
    branches:
      - feature/docker-lint
  workflow_dispatch: {}

permissions:
  contents: read
#  issues: write
#  pull-requests: write

jobs:
  vacuum-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run vacuum lint Action
        uses: ./      # since this workflow lives inside this repo, './' points to action.yml
        with:
          openapi_path: "sample-specs/burgershop.yaml"
#          ruleset: "rules/custom.rules.json"