name: "Lint OpenAPI specification using vacuum"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  vacuum-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run OpenAPI lint with vacuum
        uses: ./
        with:
          openapi_path: "sample-specs/burgershop.yaml"
          github_token: ${{ secrets.GITHUB_TOKEN }}
